trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 2
    maxParallelTrials: 1
    params:
    - parameterName: early-stop-patience
      type: INTEGER
      minValue: 5
      maxValue: 30
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: train-batch-size
      type: INTEGER
      minValue: 70
      maxValue: 500
      scaleType: UNIT_LOG_SCALE
    - parameterName: first-layer-size
      type: INTEGER
      minValue: 90
      maxValue: 300
      scaleType: UNIT_LOG_SCALE
    - parameterName: num-layers
      type: INTEGER
      minValue: 4
      maxValue: 10
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: scale-factor
      type: DOUBLE
      minValue: 0.5
      maxValue: 0.9
      scaleType: UNIT_REVERSE_LOG_SCALE
    hyperparameterMetricTag: acc
trainingOutput:
  isHyperparameterTuningJob: True
