trainingInput:
  scaleTier: BASIC_GPU
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 30
    maxParallelTrials: 3
    params:
    - parameterName: early-stop-patience
      type: INTEGER
      minValue: 50
      maxValue: 1000
      scaleType: UNIT_LOG_SCALE
    - parameterName: train-batch-size
      type: INTEGER
      minValue: 250
      maxValue: 800
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: num-layers
      type: INTEGER
      minValue: 5
      maxValue: 20
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: first-layer-size
      type: INTEGER
      minValue: 200
      maxValue: 700
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: scale-factor
      type: DOUBLE
      minValue: 0.65
      maxValue: 0.99
      scaleType: UNIT_LINEAR_SCALE
    # - parameterName: first-layer-dropout-rate
    #   type: INTEGER
    #   minValue: 0.05
    #   maxValue: 0.6
    #   scaleType: UNIT_LINEAR_SCALE
    # - parameterName: dropout-rate-scale-factor
    #   type: DOUBLE
    #   minValue: 0.5
    #   maxValue: 1
    #   scaleType: UNIT_LINEAR_SCALE
    hyperparameterMetricTag: acc
trainingOutput:
  isHyperparameterTuningJob: True
