trainingInput:
  scaleTier: BASIC_GPU
  # masterType: standard_gpu
  # workerType: standard_gpu
  # parameterServerType: standard
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 2
    maxParallelTrials: 2
    params:
    - parameterName: early-stop-patience
      type: INTEGER
      minValue: 100
      maxValue: 200
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: train-batch-size
      type: INTEGER
      minValue: 250
      maxValue: 650
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: num-layers
      type: INTEGER
      minValue: 5
      maxValue: 10
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: first-layer-size
      type: INTEGER
      minValue: 200
      maxValue: 500
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: scale-factor
      type: DOUBLE
      minValue: 0.7
      maxValue: 0.99
      scaleType: UNIT_LINEAR_SCALE
    # - parameterName: first-layer-dropout-rate
    #   type: INTEGER
    #   minValue: 0.05
    #   maxValue: 0.6
    #   scaleType: UNIT_LINEAR_SCALE
    # - parameterName: dropout-rate-scale-factor
    #   type: DOUBLE
    #   minValue: 0.5
    #   maxValue: 1
    #   scaleType: UNIT_LINEAR_SCALE
    hyperparameterMetricTag: acc
trainingOutput:
  isHyperparameterTuningJob: True
